language: java
jdk: oraclejdk8
dist: trusty
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  global:
    - DISCORD_URL=https://raw.githubusercontent.com/itachi1706/travis-ci-discord-webhook/master/send.sh
    - DISCORD_CALL = 0
before_install:
  - chmod +x gradlew
  - wget $DISCORD_URL
  - chmod +x send.sh
script: travis_retry ./gradlew assemble
after_success:
  - ./gradlew javadoc # Generate Javadocs
  - zip -r javadocs.zip ./html # Compress it
  - cp ./build/libs/*.jar ./deliverables/RRPSS.jar
  - zip -r deliverables.zip ./deliverables
  - ./send.sh success $WEBHOOK_URL
  - DISCORD_CALL=1
after_failure: 
  - ./send.sh failure $WEBHOOK_URL
  - DISCORD_CALL=1
after_script: if [ $DISCORD_CALL -eq 0 ]; then ./send.sh error $WEBHOOK_URL; fi
deploy:
  provider: releases
  api_key: "$OAUTH_KEY"
  file_glob: true
  file:
    - './build/libs/*.jar'
    - 'javadocs.zip'
    - 'deliverables.zip'
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false # Disable email notification completely
